### ISSUE TITLE
전체화면 캐시사용중 메뉴에 새글표시 모듈이 작동하지 않음.

### ISSUE THREAD

**Issue by bjrambo** [poesis/xe-supercache#1]
아마도 이 모듈의 DB쿼리를 하지 않아 생긴 문제같아요.

![_091616_012527_am](https://cloud.githubusercontent.com/assets/4381756/18558048/7607104e-7bac-11e6-820a-e5dd611b9009.jpg)

캐시시간이 지나서 지금은 캐시가 다시 활성화되어서 그런지 잘나오긴한데..ㅎㅎ;;

**Comment by kijin** [comment]
원래 캐시 기간 중에 발생한 업데이트는 반영되지 않습니다.

그래도 반영될 때는 한꺼번에 반영되어야 정상인데, 그렇지 않다면 메뉴에 새글표시 모듈이 내부적으로 사용하는 캐시 때문인 듯... 이런 경우에는 캐시 기간의 2배가 지나야 반영됩니다.

**Comment by kijin** [comment]
새 글 등록시 메인화면이나 게시판 캐시를 자동 갱신해 주는 기능이 좀더 강화되었습니다. 어제 버전은 일부 캐시가 그대로 남는 문제가 있더라고요.
