### ISSUE TITLE
모바일에서 ssl지원 애드온에 제대로 작동안하는거 같아요

### ISSUE THREAD

**Issue by jinkpark** [poesis/xe-supercache#10]
이게 저의 홈페이지에서만 그런건지 잘 모르겠는데요 
다른분 의견이 없는걸로 봐서는요

우연히 무언가를 테스트 한다고 부분ssl에서 전체 ssl로 변경을 잠시했는데요

 몇일전까지만해도 'ssl지원 애드온'때문에  모바에서 보안경고가  오늘 갑자기 생겨요

nongong.org

**Comment by jinkpark** [comment]
아. 죄송합니다.. 지금은 괜찮은거 같습니다.
일시적인 현상인거 같습니다.
애드온과 모듈을 재설정하고 잠시 시간이 지나니 괜찮네요

**Comment by kijin** [comment]
설정을 변경하면 캐시가 적용된 기간 동안 예전 설정과 현재 설정이 동시에 보일 수 있습니다.
