### ISSUE TITLE
위젯캐시도 별도 제외할수 있게....

### ISSUE THREAD

**Issue by wookho** [poesis/xe-supercache#11]
비로그인 대상자인 풀페이지캐시에서 MID별로 제외가 가능해서 제외를 해 놓은 곳인데 위젯으로 구성된 페이지이다 보니 위젯캐시에서 제외가 되지 않으니 살짝 문제가 되는 페이지들이 있는데요.. 

위젯페이지에서도 선별적으로 제외할 수 있으면 좋겠습니다. MID별로요.. 저희는 랜덤식으로 추출하는 위젯페이지들이 몇개 있어서요....

**Comment by wookho** [comment]
근데 이게 되려나요?? 가만 생각해보니 그 페이지에 포함된 위젯을 제외해야 하는 상황이네요?

**Comment by kijin** [comment]
다른 기능들처럼 mid별로 제외시키도록 할 수 있겠습니다.
