### ISSUE TITLE
포인트 현황 위젯에 캐시 적용시 올바로 나오지 않는 문제

### ISSUE THREAD

**Issue by weirdsoup** [poesis/xe-supercache#12]
https://www.xpressengine.com/index.php?mid=download&package_id=18324347

이 위젯에 위젯캐시를 적용하면 올바로 나오지 않고 뒤죽박죽으로 나오네요.

레벨 10인 사람이 30렙으로 나오고 19인데 10으로 나오고 그렇습니다. (퍼센트 부분도 당연히 제대로 안 나오더군요)

단, 적용하자마자 바로 그런건지 며칠 쓰고 나서 그렇게 된 건지는 모르겠네요.

캐시 적용 해제하고 슈퍼캐시 재생성하고 나니까 정상적으로 출력됩니다.

(다만, 저는 저 자료를 그대로 사용하는 건 아니고 라이믹스에서 php 경고 뿜는 부분 수정하고 디자인 약간 수정했습니다. 근데 그거때문에 차이가 있을 것 같지는 않네요)

**Comment by kijin** [comment]
회원마다 다른 내용이 나와야 하는 위젯이라면 당연히 위젯 캐시를 적용하시면 안됩니다.

해당 위젯은 내부 블랙리스트에 추가하도록 하겠습니다.

**Comment by weirdsoup** [comment]
아 그렇군요. 이미 위젯캐시 설명에 나와 있었네요. 감사합니다.

**Comment by wookho** [comment]
해당위젯은 로그인한 사람마다 다르게 보이는 위젯이 아닙니다. 뭐 저희는 혹시 목라 위젯캐시 적용을 제외하고 사용해서 특별히 문제점은 발견하지는 않았지만요.

이 위젯은 블랙리스트로 올라갈 위젯은 아닌것으로 생각됩니다.
회원들의 포인트를 쿼리해서 순위를 매겨 출력해주는 위젯입니다.

**Comment by weirdsoup** [comment]
링크해놓은 위젯은 로그인한 사람마다 다르게 보이는 위젯이 맞습니다. 자기 자신의 포인트 현황을 출력하는 위젯입니다. @wookho 님이 말씀하시는 위젯은 다른 종류인 것 같습니다.

**Comment by wookho** [comment]
아.. 포인트랭킹으로 잘못보았습니다. 근데 자신의 정보를 출력하는 위젯이라도 적용해도 문제는 없어야 할텐데요.. 저로서는 약간 혼돈이 생기는군요.  사실 이런 위젯은 보통 캐시를 적용하지 않아 실시간으로 포인트 변화를 즉시 반영하게 운영하는게 맞긴 하지만 캐시 시간을 주었다고 뒤죽박죽 되는건 뭔가 이상하네요.

**Comment by wookho** [comment]
글쓴이 게시글 출력위젯과 마찬가지 현상이 생기는거군요.
이해가 되었습니다. 아마 캐시생성될때의 회원번호때문에 그런거네요.

**Comment by kijin** [comment]
네, 캐시 갱신 시점에 로그인해 있던 회원의 레벨과 포인트가 이후 몇 분간 모든 회원에게 똑같이 표시될 거예요.

일일이 블랙리스트에 추가하려니 복잡하네요... 위젯 이름에 member, point, level 등이 포함되어 있는 것은 최초 사용시 기본값을 모두 "아니오"로 설정하는 편이 나을까요? 캐시 덕을 많이 보는 위젯은 대개 content 부류이니까요...

**Comment by wookho** [comment]
일괄로 블랙리스트를 올리면 부작용이 생길 수도 있으니 지금처럼 확실한 것들만 등록해 주시는게 좋을거 같습니다.

**Comment by kijin** [comment]
소스에 하드코딩된 블랙리스트가 아니라 최초 설치시 기본값을 말씀드린 것입니다. 지금은 블랙리스트를 제외한 모든 위젯이 기본값 "예"로 되어 있거든요.

**Comment by wookho** [comment]
아.. 기본값 아니오 군요. 오늘 난독증이 좀 있네요 ㅋ 전체를 아니오로 하셔도 됩니다 ㅋ

**Comment by kijin** [comment]
아니면 거꾸로 content 종류만 제외하고 모두 아니오로 하는 것도 괜찮겠네요. 모든 기본값을 아니오로 해 버리면 맨 꼭대기의 "위젯 캐시 사용"만 예로 해놓고 왜 안되냐고 하는 분들도 있을지 모르니...

**Comment by kijin** [comment]
패치했습니다.
