### ISSUE TITLE
Fatal Error 가 납니다!!

### ISSUE THREAD

**Issue by botserv** [poesis/xe-supercache#13]
supercache.controller.php	: 1079

	Fatal Error 에러가 나면서 관리자를 제외한 이용자들이 사이트 접속이 아에 안되는 현상이 있어요!!

1072      * Get the device type for full-page cache.  
1073      *   
1074      * @return string  
1075      */  
1076     public function getDeviceType()  
1077     {  
1078         // Prioritize XE official mobile device detection.  
1079         **$is_mobile_enabled = Mobile::isMobileEnabled();**  
1080           
1081         // Check the session for cached data.  
1082         if (!$is_mobile_enabled && isset($_SESSION['supercache_device_type']))  
1083         {

**Comment by kijin** [comment]
슈퍼 캐시 모듈은 XE 1.8.25 이상 버전만 공식적으로 지원합니다.

구 버전에는 Mobile::isMobileEnabled() 함수가 존재하지 않을 수도 있습니다.
