### ISSUE TITLE
슈퍼캐시 특이한(?) 증상입니다.

### ISSUE THREAD

**Issue by woosungchoi** [poesis/xe-supercache#18]
아마 알고 계실 듯 합니다만
 
메인 화면 위젯 -> 게시물로 들어갈 시
Status Code:301 뜨면 x-supercache:MISS

게시판 목록 -> 게시물로 들어갈 시
Status Code:200 뜨면 x-supercache:HIT  뜨네요.

그리고 F5 를 눌렀을 때도 304가 나오면서 MISS가 뜨더라구요.

301과 304도 HIT이 뜨게 할 순 없을까요?

 
F12로 테스트하면서 슈퍼캐시가 적용된 홈페이지들을 둘러봤는데 모두 같은 증상이 나타나더군요.
 
보통 메인페이지의 최신글 목록을 보고 실제 게시물로 들어가는 상황이 많이 있기 때문에
 
이런 증상이 해결되면 좋겠습니다.

**Comment by kijin** [comment]
의도적인 동작입니다. mid가 누락된 주소에서 mid가 포함된 주소로 리다이렉트할 때는 실제 모듈을 실행하지 않고 `ModuleHandler::init()` 단계에서 종료되므로 굳이 슈퍼 캐시가 끼어들 필요가 없습니다. 301 리다이렉트 후에 표시되는 게시물 페이지에서만 HIT이 나오면 됩니다.

Cache-Control 헤더 사용 옵션을 켜두신 경우 (권장하지 않습니다) 304를 반환할 수도 있는데, 이 경우 HIT가 표시되어야 정상입니다. MISS라면 뭔가 이상하네요.

**Comment by woosungchoi** [comment]
아 Cache-Control 헤더 사용 옵션을 켜두었습니다. 이간 꺼야겠군요! 이만 닫겠습니다. 감사합니다.
