### ISSUE TITLE
쿠키가 문제가 되는지 특정페이지에서 발생한 팝업 쿠키가 작동하지 않는듯 합니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-supercache#2]
현재 제 컴에서 위 페이지에서만 팝업이 뜨고 있습니다. 어떤 페이지에서든 뜨게 설정된 팝업인데 현재 위 페이지에서 오늘만보기 버튼으로 팝업을 더 이상 뜨지 않게 해도 계속 팝업이 뜨는 현상이 발생하네요.

**Comment by wookho** [comment]
캐시시간이 적용되어 그런지 이제는 또 뜨지 않네요.

**Comment by wookho** [comment]
아까 떴던 팝업이 제 PC의 쿠키와 상관없이 떴던게 아닌가 의심이 됩니다.  한 페이지에서만 떴던 것으로 보아 슈퍼캐시모듈에의해 캐시된 것이 보여져서 자꾸 팝업이 떴었던거 같습니다. 다른 방문자나 로봇에의해 떴던 팝업동작이 저에게도 영향을 주는거 같은 생각? 입니다.

**Comment by kijin** [comment]
네. 팝업 표시 여부를 레이아웃 HTML에서 판단하고 있는 것 같습니다. 전체화면 캐시 사용시 로그인하지 않은 모든 사용자가 똑같은 HTML 컨텐츠를 보게 되므로, 레이아웃 HTML에서 방문자를 차별(?)하는 기능은 사용할 수 없게 됩니다.

사용자가 설정한 쿠키 값에 따라 캐시를 분리하는 기능을 계획중입니다만, 방문자를 다양하게 구분할수록 캐시 효율이 떨어지게 됩니다. 현재는 PC/모바일, HTTP/HTTPS 정도만 구분하고 있습니다.

가장 좋은 방법은 팝업 표시 여부를 자바스크립트에서 판단하도록 수정하는 것입니다.

**Comment by wookho** [comment]
제가 사용하는 애드온을 첨부해드리면 도움이 되실까요? 제것은 유료 애드온이긴 하지만 비슷한 방식이 많을텐데요. 일단 첨부해 드립니다. 확인하시면 첨부는 지우겠습니다.

**Comment by kijin** [comment]
확인했습니다.

**Comment by kijin** [comment]
`tpl/main.html`에서 맨 위와 아래에 있는 XE 템플릿 조건문을 지우고, 그 대신 `js/Xharpen_LightBox.js`에서 22~26줄(`$d.ready`로 시작하는 부분)을 아래와 같은 조건문으로 묶어 보세요.

```
if(!document.cookie || document.cookie.indexOf('xharpen_light_box') < 0) {
    // 22~26줄에 원래 있던 내용
} else {
    $(".xharpen-lightBox-container").remove();
}
```

HTML 컨텐츠는 항상 똑같이 출력하되, 쿠키가 없을 때만 애니메이션을 실행하고 쿠키가 있으면 lightbox를 삭제하는 코드입니다.

**Comment by wookho** [comment]
말씀하신대로 처리해 보았는데 랜덤하게 페이지에서 팝업이 뜹니다만 닫기 버튼으로 더 이상 안뜨는 동작이 먹히지 않네요.

**Comment by kijin** [comment]
원상복구하고, 쿠키에 따라 전체화면 캐시를 별도 적용하는 기능이 완성된 후에 다시 테스트해 주시면 감사하겠습니다.

**Comment by wookho** [comment]
네. 알겠습니다.

**Comment by wookho** [comment]
해당 애드온에 비회원에게는 동작하지 않는 코드를 당분간 추가해 놓으면 일단 사이트 방문시 불편은 팝업으로 인한 것은 없앨 수 있을 듯 하네요. 나중에 해결이 된다면 비회원에게도 팝업을 다시 노출하도록 하겠습니다.

**Comment by kijin** [comment]
쿠키 값에 따라 캐시를 분리하는 기능을 넣었습니다.

master 브랜치 업데이트 후 "별도로 캐시할 쿠키" 옵션에 `xharpen_light_box`를 넣어 보세요.

**Comment by wookho** [comment]
감사합니다. 새로 다운받아 말씀하신대로 설정했더니 비로그인으로 팝업 닫기 후 쿠키작동으로 다시 팝업이 뜨지 않고 정상적으로 이용이 가능하네요.

**Comment by kijin** [comment]
오오~ 포메러브 TTFB값이 300ms에서 30ms로 열 배나 빨라졌어요! ㅋㅋ

**Comment by wookho** [comment]
굉장합니다~
