### ISSUE TITLE
검색 결과 캐시 사용시 계속검색이 한번만 나오는 문제

### ISSUE THREAD

**Issue by nabiryu** [poesis/xe-supercache#23]
검색 결과 캐시를 끄고
게시판검색시 계속검색 버튼이 7~8회 나오는 반면

검색결과 캐시를 켜고
동일한 검색어 입력하여 검색시 계속검색 버튼이 최초에만 나옵니다.

**Comment by eondcom** [comment]
xe 최신버전에서 다시 동일한 문제가 나타납니다. xe 최신버전에서 해당 기능이 뭔가 다시 이런 문제가 나타나는 원인이 있을까요.

**Comment by eondcom** [comment]
검색결과 캐시를 끄거나 주기를 조정하는 식으로 일단 해결했습니다.
