### ISSUE TITLE
관리자 페이지에서 슈퍼캐시에 접속이 안됩니다.

### ISSUE THREAD

**Issue by xiaopiao** [poesis/xe-supercache#26]
관리자페이지>설치된모듈>슈퍼캐시 클릭시
잘못된 요청입니다.
classes/module/ModuleHandler.class.php:448
돌아가기

이런 에러가 노출됩니다.

환경은 aapanel과 DirectAdmin 기본 구성된 기본 환경입니다.
php 8에서도 동일한 현상이 발생합니다
rhymix_version : 2.0.1
php : 7.2.34 (64-bit)
server : Apache/2
sapi : fpm-fcgi
db.version : 5.7.31

**Comment by xiaopiao** [comment]
라이믹스 2.0.1 의 모듈 폴터에 슈퍼캐시 최신 버전 넣고 업로드후 설치하면 오류가 발생합니다.
php8.0입니다.

**Comment by kijin** [comment]
rhymix/rhymix#1531 해결
