### ISSUE TITLE
라이믹스 gzip 압축시 사이트먹통 문제

### ISSUE THREAD

**Issue by HyUnSeunGsEo** [poesis/xe-supercache#27]
라이믹스 사이트설정에 gzip 압축 설정이 있는데 그거 활성화하고 저장하면 먹통이 됩니다.

계정자체가요.

왜그런거죠?

**Comment by kijin** [comment]
라이믹스의 gzip 설정을 켜신 건가요, 아니면 슈퍼캐시의 gzip 설정 말씀이신가요?

라이믹스 설정과 관련된 문제라면 번지수 잘못 찾으셨습니다.

어느 쪽이든 상관없이, PHP단에서 gzip은 사용하지 않는 것을 권장합니다. 아파치, nginx 등 대부분의 웹서버에서 훨씬 더 효율적인 방식으로 자동으로 gzip 적용이 됩니다.
