### ISSUE TITLE
PHP Warning: Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by shydah** [poesis/xe-supercache#28]
**Errors (1)**
```
01. Warning: Illegal offset type in isset or empty
modules/supercache/supercache.controller.php:138
classes/module/ModuleHandler.class.php:1258
modules/document/document.model.php:250
modules/board/board.view.php:589
modules/board/board.view.php:193
classes/module/ModuleObject.class.php:687
classes/module/ModuleHandler.class.php:662
index.php:52
```

환경은 Rhymix 2.0.13 / PHP 7.4.21 (FPM) / Ubuntu 20.04 LTS입니다.
타임라인 게시판에 들어가자 디버그창에 이런 Warning이 잡혀 제보드립니다.

**Comment by shydah** [comment]
생각해보니까 이건 타임라인 모듈 쪽에 먼저 문의를 해야 할 내용 같네요.
피곤해서 첫줄만 보고 엉뚱한 데다 제보한 듯 합니다 ^^;;

**Comment by eondcom** [comment]
> 생각해보니까 이건 타임라인 모듈 쪽에 먼저 문의를 해야 할 내용 같네요. 피곤해서 첫줄만 보고 엉뚱한 데다 제보한 듯 합니다 ^^;;

안녕하세요. 혹시 이 문제 해결 하셨나요?

**Comment by kijin** [comment]
@eondcom 현재 master 브랜치의 코드 기준으로는 138줄에 illegal offset type 경고를 일으킬 만한 부분이 보이지 않습니다. #32 #33 #34 에서 상당부분 수정되었는데, 만약 다른 줄에서 비슷한 경고가 뜬다면 어느 줄인지 제보 부탁드립니다.

**Comment by eondcom** [comment]
> @eondcom 현재 master 브랜치의 코드 기준으로는 138줄에 illegal offset type 경고를 일으킬 만한 부분이 보이지 않습니다. #32 #33 #34 에서 상당부분 수정되었는데, 만약 다른 줄에서 비슷한 경고가 뜬다면 어느 줄인지 제보 부탁드립니다.

위에 shydah님 코멘트 보면 이게 타임라인 모듈 쪽 오류인거 같아서 해결되었냐고 물어봤습니다. 지금 확인되는 이슈는 타임라인 모듈 + 슈퍼캐시 모듈 사용시, 검색했을 때 해당 오류가 뜨는 것으로 확인됩니다.
