### ISSUE TITLE
[질문] 라이믹스 압축 기능 및 minify 기능과 함께 사용 문의

### ISSUE THREAD

**Issue by socialskyo** [poesis/xe-supercache#3]
기진곰님 궁금한게 있어서 문의 드립니다.
1. 공홈 에 있는 minify 팁 :  https://www.xpressengine.com/tip/19979181
2. 라이믹스 고급 설정 옵션에 있는 gzip 압축 기능 
3. 라이믹스 고급 설정에 있는 스크립트 자동 압축 
4. 라이믹스 고급 설정에 있는 스크립트 합치기

질문1 , 위 4가지 기능과 이 슈퍼캐시 모듈을 모두 같이 사용해도 되겠죠? 캐시와 압축은 다른거라 하셨으니까요. 특히 1번은 글내용을 보면 캐시라는 말을 사용을 하고 있어서 헷갈립니다.

아래 질문은 라이믹스 git에서 여쭤봐야 할것 같긴한데 질문 남긴김에 적어 봅니다.

질문2, 만약 위 1번 팁의 minify 기능이 캐시가 아니라면 라이믹스의 2번 3번 기능과 중첩인듯한 느낌이 드는데 중복 사용해야 하는건지, 아니면 라이믹스 압축 기능만으로 충분한건지 헷갈립니다.

질문3, 2번과 3번은 다른 기능인가요? -

**Comment by kijin** [comment]
1번은 라이믹스와 충돌할 가능성이 높은 팁입니다. 5년 전 기준이기도 하고요.

minify와 gzip은 전혀 별개의 기법이고, 두 가지 모두 사용하는 것이 좋습니다. minify는 라이믹스의 3번 기능으로 사용하시면 되고, gzip 압축은 라이믹스에서 지원하지 않으므로 웹서버 설정으로 대체하시면 됩니다. 아파치의 .htaccess나 nginx 설정을 사용해서 모든 CSS, JS 파일을 gzip 압축하여 전송하도록 하면 PHP(라이믹스)는 전혀 관여할 필요가 없기 때문에 성능이 더 좋아집니다.

2~4번은 사용하셔도 무방합니다.

gzip 압축을 켜면 네이버 로봇이 못 긁어가는 경우가 있다는 얘기를 종종 듣습니다. 만약 이런 문제가 발생한다면 라이믹스에서는 gzip을 켜시고, 슈퍼캐시 모듈의 "기타 설정" 페이지에서 네이버 로봇은 gzip 압축을 적용하지 않는 옵션을 선택해 보세요. 코어에서는 on/off만 지원하는 gzip 압축을 좀더 세부적으로 조절할 수 있는 기능입니다.

**Comment by socialskyo** [comment]
@kijin 네. 시원한 답변 감사합니다. 그리 하겠습니다.
