### ISSUE TITLE
PHP 8.0에서 코어와 충돌 이슈

### ISSUE THREAD

**Issue by Waterticket** [poesis/xe-supercache#31]
라이믹스 2.0.17(main branch), PHP 8.0 환경에서, 슈퍼캐시 모듈 설치 후 메뉴 수정 메뉴에 들어갔습니다.

그랬더니 아래와 같은 오류가 떴습니다
```서버 오류 Error #0 "Attempt to assign property "defaultSkin" on bool" in modules/menu/menu.admin.model.php on line 367```

처음에는 코어 오류인줄 알고, 357번째 줄 아래에 ```if($module == false) continue;``` 를 추가하여 오류가 사라지는 모습을 보았습니다
https://github.com/rhymix/rhymix/blob/4153b1064516a52c9cb8009dbf49af04c45ecc1c/modules/menu/menu.admin.model.php#L354-L357

그런데, 혹시 몰라서 라이믹스 관리자 페이지 아래에 있는 캐시파일 재생성을 클릭하여 캐시를 삭제하니, 어드민 페이지 전역에서 아래와 같은 오류가 뜨게 되었습니다.
```Error #0 "Attempt to assign property "module" on bool" in modules/module/module.model.php on line 1368```

좀 더 테스트를 해보려고 했으나, 오래 걸릴것 같아서 일단 제보 남기고 찾아보려고 합니다

**Comment by kijin** [comment]
메뉴 부분은 슈퍼캐시가 관여하지 않을 테고, 관리자 화면이라면 당연히 로그인되어 있어서 전체화면 캐시도 작동하지 않고 있을 텐데 이상하네요. 혹시 게시판 캐시나 위젯 캐시 등 특정 기능 사용시에만 문제가 생기는지, 아니면 슈퍼캐시 모듈을 설치해 두기만 해도 문제가 생기는지 확인 가능할까요?

**Comment by Waterticket** [comment]
계속 테스트 하는데도 오류가 연쇄적으로 발생해서, 다음날에 처음부터 다시 설치해보았는데 정상적으로 작동하네요;

호스팅 환경에서 적용하다 오류난거라, 아마 트래픽 초과랑 뭔가 연관이 있는것 같은데 지금와서는 알아볼 길이 없네요 ㅎㅎ..

좀 더 길게 보지않은 제 미스네요 ㅜㅜ

코어에도 슈퍼캐시 모듈에도 문제가 없어보이니 이 이슈는 닫겠습니다!
