### ISSUE TITLE
[오류] 검색캐시 활성화, 통합 검색결과 > 게시물 > 삭제시 오류

### ISSUE THREAD

**Issue by gosugoon** [poesis/xe-supercache#4]
Member function .. 어쩌구 에러.
검색캐시 사용시에는 문제가 없으나
검색캐시 사용 & 문서 갱신 & 댓글 갱신 체크시 에러..

저만 그러는거면 다행인데.. 확인 요청

**Comment by kijin** [comment]
제 컴퓨터에서는 오류가 발생하지 않습니다. Member function 이후에 뭐라고 나오는지 파일명, 줄번호를 포함하여 알려주세요.

**Comment by gosugoon** [comment]
PHP Fatal Error: Call to a member function deleteSearchResultCache() on a non-object in modules/supercache/supercache.controller.php on line 491
게시판 검색에서 문서/댓글 갱신을 선택하고 검색을 한번 한뒤에 삭제하면 이렇게 에러가 납니다.
문서는 삭제는 됩니다.
index.php?mid=sitenews&search_target=title_content&search_keyword=%EC%95%88%EB%82%B4&document_srl=18163901&act=dispBoardDelete 삭제버튼 화면의 URL 입니다.

**Comment by kijin** [comment]
아, 댓글이 달린 문서를 삭제하면 문서 삭제는 잘 되는데 댓글 삭제 도중 오류가 나고 있었군요.

전체화면 캐시를 사용하지 않거나 전체화면 캐시에서 댓글 작성시 아무 작업을 하지 않도록 설정한 상태에서 검색 결과 캐시를 사용하는 경우에만 일어나는... 꽤 애매한 버그였습니다 ㅠ

정확히 알려주셔서 감사합니다. 지금 곧 패치하겠습니다.
