### ISSUE TITLE
위젯캐시 기능 사용중

### ISSUE THREAD

**Issue by wookho** [poesis/xe-supercache#6]
https://www.xetown.com/index.php?mid=xepoint&category=17121&document_srl=286492

글쓴이 게시물 출력위젯 이 이상동작을 합니다.
목록에 5개를 설정해서 잘 출력했었는데 슈퍼캐시의 위젯캐시기능을 적용하니 2개가 출력되네요. 또는 1개 이렇게 부족한 목록으로 출력이 되네요.

**Comment by wookho** [comment]
증상을 확인해보니 슈퍼캐시를 적용하면 글쓴이가 아닌 이전에 캐시될때 글쓴이의 목록으로 가져와서 발생되는 문제입니다. 

이 위젯 개발될때도 문제가 되었던 부분이라 제가 문의해서 고쳐진 내용입니다.

**Comment by kijin** [comment]
글에 따라 내용이 달라져야 하는 위젯이라면 슈퍼캐시를 적용하면 안 됩니다. 위젯 자체적으로 캐시를 구현할 수는 있겠지요.

위젯 성격상 슈퍼캐시가 건드려서는 안 되는 것이 있다면 자체 블랙리스트에 등록하여 캐시 적용을 막도록 하겠습니다. 이미 login_info 위젯이 블랙리스트에 등록되어 있습니다^^

**Comment by wookho** [comment]
아. 슈퍼캐시에서 컨트롤 하지 못하는 부분이군요. 알겠습니다. 이 위젯은 사용하지 않도록 하겠습니다.

**Comment by kijin** [comment]
Fixed in 9915fd2
