### ISSUE TITLE
지금 커밋 적용하고 사이트 에러가 납니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-supercache#7]
![error](https://cloud.githubusercontent.com/assets/6590236/20331767/e08d55ae-abea-11e6-9517-ee25d2b50912.PNG)

일단 폴더명을 바꾸어 놓아 사이트 접속은 되게 해 놓았습니다.

**Comment by wookho** [comment]
Call to undefined method Context::getSessionStatus()
/public_html/xe/modules/supercache/supercache.controller.php : 1051

**Comment by kijin** [comment]
어젯밤에 지저분한 코드를 정리하다가 괄호를 날려먹었나 봐요;;

1051줄의 조건 3개 중 2,3번째를 괄호로 묶어 주세요.

**Comment by wookho** [comment]
if (!$is_mobile_enabled && (!method_exists('Context', 'getSessionStatus') || Context::getSessionStatus()))

요렇게 하니 사이트가 열리네요.
