### ISSUE TITLE
세진님 내가작성한 댓글 모듈 에러가 나는데요.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-supercache#8]
OOPS!

Fatal Error: Unknown: The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;commentItem&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition

이자료가 캐시를 사용하는 것으로 알고 있습니다. 에러가 생긴게 어제부터라서 살펴봐주세요.

**Comment by wookho** [comment]
```
./classes/template/TemplateHandler.class.php(390) : eval()'d code : 33
```

383
            {  
384
                include(substr($buff, 7));  
385
            }  
386
        }  
387
        else  
388
        {  
389
            $eval_str = "?>" . $buff;  
390
            @eval($eval_str);  
391
            $error_info = error_get_last();  
392
            //parse error  
393
            if ($error_info['type'] == 4)  
394
            {  
395
                throw new Exception("Error Parsing Template - {$error_info['message']} in template file {$this->file}");  
396
            }  
397
        }

**Comment by wookho** [comment]
증상이 처음한번은 잘 보이고 이후 다시 내댓글 보기 하면 저렇게 에러가 뜹니다.

**Comment by wookho** [comment]
일단 슈퍼캐시의 위젯캐시 기능을 잠시 끄자마자 테스트 해 보니 동일한 현상이 나타납니다.
아마도 슈퍼캐시와 무관한 저 자료의 문제로 보이는데요.

슈퍼캐시 위젯캐시를 끄고 오래 기다린다음 테스트를 해야 하는 것이라면 제가 테스트가 부족했을 수도 있겠지만 일단 저는 위젯캐시를 끄고 동일한 현상을 확인했으니 슈퍼캐시와  무관하다면 닫아주세요~

**Comment by kijin** [comment]
일단 의심가는 부분이 있기는 합니다. 들어가서 확인해 보겠습니다.

페이징 캐시 또는 검색결과 캐시 사용 여부에 따라 차이가 있는지 확인 부탁드립니다.

**Comment by wookho** [comment]
페이징캐시사용,오프셋쿼리사용,검색결과캐시사용 세가지 모두 미사용으로 해도 마찬가지 증상이네요.

**Comment by wookho** [comment]
https://www.xpressengine.com/index.php?mid=download&package_id=21211103
공홈에 같은 에러를 문의하시는 분도 슈퍼캐시를 사용하기는 하시는 듯 합니다.

**Comment by wookho** [comment]
슈퍼캐시모듈의 개입을 잠시 막기위해 폴더명을 변경한 후 테스트를 해보니 마찬가지로 2번째 조회시 에러가 발생하네요. 이정도면 슈퍼캐시모듈과는 상관없는 오류죠?

**Comment by kijin** [comment]
XE 클래스 오토로딩 목록에서 `commentItem` 클래스가 누락되어 발생하는 문제로 보입니다.
config/config.inc.php 320줄 전후에 아래의 내용을 추가해 보세요.

```
'commentItem' => 'modules/comment/comment.item.php',
```

**Comment by wookho** [comment]
감사합니다. 말씀해주신대로 수정하니 잘 됩니다. 감사합니다.

**Comment by kijin** [comment]
XE에서 언제 패치될지 알 수 없고, 예전 버전에서 슈퍼 캐시 사용을 원하시는 분도 있을 테니 슈퍼 캐시 쪽에서도 간단한 대응책을 마련해 놓겠습니다. (오토로더 추가 등록 - 패치된 XE에서는 성능에 영향 없음)
